name: Cleanup old images

on:
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Delete untagged image versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: sbox-server-native-linux
          package-type: container
          min-versions-to-keep: 5
          delete-only-untagged-versions: 'true'